### ISSUE TITLE
Northern never gets set

### ISSUE THREAD

**Issue by danielsiwiec** [TimothyGu/utm#1]
A bug in the code prevents `northern` from being set

**Comment by TimothyGu** [comment]
I've published v1.0.1 which includes a fix for this issue. @danielsiwiec, I also invited you to become a collaborator of this repo, and added you as an owner on npm.

**Comment by danielsiwiec** [comment]
Thanks. I'll try to add some unit tests for this if I find some spare time

**Comment by TimothyGu** [comment]
Thanks! FWIW there are some existing tests in the original [Python version](https://github.com/Turbo87/utm/blob/master/test/test_utm.py) already, so you can probably just port them over.
